
package editor;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author Michael
 */
public class AboutDialog extends javax.swing.JDialog {
    
    private static final Logger LOG = Logger.getLogger(AboutDialog.class.getName());
    
    private static final String GITHUB_LINK = "https://github.com/mmyers/eug";
    private static final String EU3_THREAD = "https://forum.paradoxplaza.com/forum/index.php?threads/clausewitz-save-game-and-scenario-editor-viewer.527308/";
    private static final String EU4_THREAD = "https://forum.paradoxplaza.com/forum/index.php?threads/announcing-a-scenario-editor-and-map-viewer.707474/";
    private static final String CK3_THREAD = "https://forum.paradoxplaza.com/forum/threads/tool-clausewitz-scenario-editor-now-for-ck3.1689106/";
    private static final String PATREON_LINK = "https://www.patreon.com/user?u=60455822";
    private static final String DISCORD_LINK = "https://discord.gg/j382dvC3Fw";
    
    private static final String PARADOX_ICON = AboutDialog.class.getResource("/images/pdx-icon-32x32.png").toString();
    private static final String GITHUB_ICON = AboutDialog.class.getResource("/images/GitHub-Mark-32px.png").toString();
    private static final String DISCORD_ICON = AboutDialog.class.getResource("/images/Discord-Logo-Color.png").toString();
    private static final String PATREON_ICON = AboutDialog.class.getResource("/images/Digital-Patreon-Logo_FieryCoral.png").toString();
    
    private static final String ABOUT_TEXT =
            "<html><head><style>img { margin-right: 5px }</style></head><body style='font-size:1.2em; font-family: \"Garamond\", serif; background-color: #d3d3d3; margin-left: 5px;'>" +
            "<h1>Clausewitz Scenario Editor " + Version.getCurrentVersion() + "</h1>\n" +
            "By MichaelM<br>Since 2007<p>\n" +
            "<img src=\"" + PARADOX_ICON + "\" width=16 height=16>&nbsp;<a href=\"" + CK3_THREAD   + "\">Visit the CK3 forum thread</a><br>\n" +
            "<img src=\"" + PARADOX_ICON + "\" width=16 height=16>&nbsp;<a href=\"" + EU4_THREAD   + "\">Visit the EU4 forum thread</a><br>\n" +
            "<img src=\"" + PARADOX_ICON + "\" width=16 height=16>&nbsp;<a href=\"" + EU3_THREAD   + "\">Visit the old EU3 forum thread</a><br>\n" +
            "<img src=\"" + GITHUB_ICON  + "\" width=16 height=16>&nbsp;<a href=\"" + GITHUB_LINK  + "\">View source code on GitHub</a><br>\n" +
            "<img src=\"" + DISCORD_ICON + "\" width=16 height=16>&nbsp;<a href=\"" + DISCORD_LINK + "\">Chat with me on Discord</a><br>\n" +
            "<img src=\"" + PATREON_ICON + "\" width=16 height=16>&nbsp;<a href=\"" + PATREON_LINK + "\">Support development on Patreon</a></body></html>";

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JEditorPane aboutPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        statusLabel.setText(" ");
        getContentPane().add(statusLabel, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(380, 300));

        aboutPane.setEditable(false);
        aboutPane.setEditorKit(javax.swing.JEditorPane.createEditorKitForContentType("text/html")
        );
        aboutPane.setText(ABOUT_TEXT);
        aboutPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                aboutPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(aboutPane);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_aboutPaneHyperlinkUpdate
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                Desktop.getDesktop().browse(evt.getURL().toURI());
            } catch (URISyntaxException | IOException ex) {
                LOG.log(Level.SEVERE, "Failed to browse to " + evt.getURL().toString(), ex);
            }
        } else if (evt.getEventType() == HyperlinkEvent.EventType.ENTERED) {
            statusLabel.setText(evt.getURL().toString());
        } else if (evt.getEventType() == HyperlinkEvent.EventType.EXITED) {
            statusLabel.setText(" ");
        }
    }//GEN-LAST:event_aboutPaneHyperlinkUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
