# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    
    # Build all four main projects
    - name: Build eugFile
      run: ant -noinput -buildfile eugFile/build.xml
    - name: Build EugFile_specific
      run: ant -noinput -buildfile EugFile_specific/build.xml
      env:
        project.EugFile: ../EugFile
    - name: Build EugSyntax
      run: ant -noinput -buildfile EugSyntax/build.xml
      env:
        project.EugFile: ../EugFile
    - name: Build Scenario Editor
      run: ant -noinput -buildfile EU3_Scenario_Editor/build.xml
      env:
        project.EugFile: ../EugFile
        project.EugFile_specific: ../EugFile_specific
        project.EugSyntax: ../EugSyntax
        
    # CodeQL
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      
    # Artifact upload
    - name: Upload EugFile artifact
      uses: actions/upload-artifact@v4
      with:
        name: EugFile
        path: eugFile/dist/eugFile.jar
    - name: Upload EugFile_specific artifact
      uses: actions/upload-artifact@v4
      with:
        name: EugFile_specific
        path: EugFile_specific/dist/EugFile_specific.jar
    - name: Upload EugSyntax artifact
      uses: actions/upload-artifact@v4
      with:
        name: EugSyntax
        path: EugSyntax/dist/EugSyntax.jar
    - name: Upload scenario editor snapshot artifact
      uses: actions/upload-artifact@v4
      with:
        name: Scenario_Editor
        path: EU3_Scenario_Editor/Scenario_Editor.zip
